#! /bin/bash

alias code="code --extensions-dir \"$XDG_DATA_HOME\"/vscode"
alias ls='ls --color=auto'
alias ll='ls -l --color=auto'
alias lla='ls -la --color=auto'
alias reboot="sudo reboot"
alias shutdown="sudo shutdown"
alias vim="nvim"
