#! /bin/bash

# Add .local/bin/ and any sub-directories to the path variable. A colon ":"
# character is automatically prepended to each directory.
#
export PATH="${PATH}$(find ~/.local/bin -type d -printf :%p):~/scripts"

# Default Programs:
export EDITOR="nvim"
export TERMINAL="gnome-terminal"
export BROWSER="brave"

# Aliases:
alias code="code --extensions-dir ${XDG_DATA_HOME}/vscode"
alias ls='ls --color=auto'
alias ll='ls -l'
alias reboot="sudo reboot"
alias shutdown="sudo shutdown"
alias vim="nvim"

# Home directory clean-up"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-$HOME/.runtime}"
export NODE_REPL_HISTORY="${XDG_DATA_HOME:-$HOME/.local/share}/node/node_repl_history"
export PYTHONSTARTUP="${XDG_CONFIG_HOME:-$HOME/.config}/python/pythonrc"
export GTK2_RC_FILES="${XDG_CONFIG_HOME:-$HOME/.config}/gtkrc-2.0"
export NPM_CONFIG_USERCONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/npm/npmrc"
export TERMINFO="${XDG_DATA_HOME:-$HOME/.local/share}"/terminfo

# Modify the system terminfo search path to prefer the environment variable set
# by this script.
#
export TERMINFO_DIRS="$TERMINFO":/usr/share/terminfo

# Only display 9 directories of the working directory in the prompt. 
#
export PROMPT_DIRTRIM=9

# My prompt
# Breaking the prompt line down:
# \[\e[1;35m\]       -- the color sequence for bright purple
# \w                 -- pwd (PROMPT_DIRTRIM modifies this)
# \n                 -- start a new line
# \[\e[1;92m\]       -- the color sequence for bright green
# \$(git branch ...) -- shell command to display the git branch
# \[\e[1;31m\]       -- the color sequence for bright red
# \$                 -- just display a $
# \[\e[m\]           -- end the previous color sequence
# 
# Breaking down the shell command to display the git branch
# git branch                     -- run the branch command from git
# 2> /dev/null                   -- ignore error messages (i.e. not a git repo)
# | sed                          -- pipe the output of that command to sed
# -e '/^[^*]/d'                  -- delete lines without a leading *
# -e 's/* \(.*\)/ [branch: \1]/' -- display branch name
#
export PS1="\[\e[1;35m\]\w\n\[\e[1;92m\]\$(git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/[\1] /')\[\e[1;31m\]\$ \[\e[m\]"

# Apply blue light filtering using redshift.
# -P reset reshift before applying changes
# -O one shot set the color temperature
# -b set the screen brightness for day:night
#
redshift -P -O 2500 2>&1>/dev/null
