#! /bin/bash

# Set the XDG directory variables to make it
# easier to source the other scripts.
#
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-$HOME/.runtime}" # often already implemented

# Configure all the environment variables
#
source "${XDG_CONFIG_HOME}/shell/env_vars"

# Modify the PATH variable.
#
source "${XDG_CONFIG_HOME}/shell/path_mods"

# Configure the aliases here just in case some
# background scripts rely on them.
#
source "${XDG_CONFIG_HOME}/shell/aliases"

# Apply blue light filtering using redshift.
# -P reset reshift before applying changes
# -O one shot set the color temperature
# -b set the screen brightness for day:night
#
redshift -P -O 3250 -b1.00:1.00 >/dev/null 2>&1
